### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by deepu105** [KyleKorndoerfer/BracketsUML#13]
Installation fails in Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 

I was trying to install from Git url and from zip, Is this listed in Brackets plugin page?

**Comment by KyleKorndoerfer** [comment]
I have not published the extension yet as there are still a few bugs/features I would like to wrap up before I do (only with sequence support to start). I've been busy with other work at the moment and have honestly not tried to install it yet through the extension manager. I've just been developing it from within my extensions folder. I'll try to look at it this weekend and see what I can do.

You could try to manually pull the source and place it inside a folder in your brackets extension folder (Help | Show Extensions Folder).

**Comment by KyleKorndoerfer** [comment]
_(finally able to spend some time on this project)_

After looking into this, I believe that the issue was that the `name` property of the `package.json` file was causing the installation issues. The proper format for the `name` property is to be all lower case, no spaces, dashes and underscores allowed ([package.json documentation](https://docs.npmjs.com/getting-started/using-a-package.json)). After making this change and adding the extension to a clean instance of Brackets (via drag-n-drop zip file) it installed and worked successfully.
