### ISSUE TITLE
!include not working

### ISSUE THREAD

**Issue by adlergfx** [KyleKorndoerfer/BracketsUML#19]
Hello, 
create work with the plugin. I have a file with multiple "!include" composed from subdiagrams (class). I got the error message that he can not find the included files. 

I open directly the folder with all files. All files are in same hierarchy level. Is there some "hidden" possibility to set the search path, did i miss something or did i found a bug?

Greetings

**Comment by KyleKorndoerfer** [comment]
The way the plugin works is that it takes the text from the open editor window, encodes it, and makes a call against the PlantUML servlet hosted at plantuml.com. Because of this it doesn't have direct access to the contents of the files referenced by the "!include" directives to bundle them up and send to the server as well.

This plugin was created to have a lightweight, cross-platform way to create PlantUML diagrams and the Brackets editor fit that use case initially. Since then, Visual Studio Code has been released and a very good PlantUML plugin was created and I have switched to using that instead. Therefore there have been no updates to this plugin since then.
